# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
# Use a package of configuration called an orb.
jobs:
  build-wheel:
    working_directory: ~/kwiver_wheels
    machine: true
    steps:
      - checkout
      - run:
          name: "Test cwd"
          command: |
            echo $CIRCLE_WORKING_DIRECTORY
      - run:
          name: "Test Docker"
          command: |
            docker version

workflows:
  # Orchestrate or schedule a set of jobs
  version: 2
  Build-Kwiver-Wheels:
      jobs:
        - build-wheel:
            filters:
              branches:
                only: master
          
