# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
# Use a package of configuration called an orb.
jobs:
  build-wheel:
    working_directory: ~/kwiver_wheels
    machine: true
    steps:
      - checkout
      - run:
          name: "Test Docker Install"
          command: |
            docker version
      - run:
          name: "Build Docker Image"
          command: |
            chmod +x build_docker.sh
            ./build_docker.sh
      - store_artifacts:
          path: ~/kwiver_wheels/pages
      - run:
          name: Install pv
          command: |
            sudo apt-get update
            sudo apt-get install -y pv
      - run:
          name: Archive docker image
          command: docker save kwiver:wheels | pv > liw_docker.tar
      - store_artifacts:
          path: ./liw_docker.tar
      - run:
          name: "Checkout Pages"
          command: |
            git checkout -f -B pages --track origin/pages
      - run:
          name: "Upload Wheels"
          command: |
            cd pages
            git add *.whl && git add index.html && git commit -m"Upload Wheel" && git push -f

workflows:
  # Orchestrate or schedule a set of jobs
  version: 2
  Build-Kwiver-Wheels:
      jobs:
        - build-wheel:
            filters:
              branches:
                only: master
          
