version: 2
jobs:
  build-wheel:
    working_directory: ~/kwiver_wheels
    machine: true
    steps:
      - checkout
      - run:
          name: "Install pv"
          command: |
            sudo apt-get update
            sudo apt-get install -y pv
      - run:
          name: "Setup Docker"
          command: |
            docker pull quay.io/pypa/manylinux2014_x86_64:latest

      # Get fletch current HEAD commit SHA
      - run:
          name: "Check Fletch update"
          command: |
            git ls-remote https://github.com/kitware/fletch.git | awk "/HEAD/ {print \$1}" > checkFletch

      # Validate vs cached check
      - restore_cache:
          keys:
            - fletch-{{ checksum "checkFletch" }}

      # Build fletch image
      - run:
          name: "Build Fletch Image"
          command: |
            chmod +x build_fletch.sh
            ./build_fletch.sh
      - run:
          name: "Archive Fletch Docker Image"
          command: docker save fletch_py37:latest | pv > fpyi_docker.tar

      - save_cache:
          key: fletch-{{ checksum "checkFletch" }}
          paths:
            - ./fpyi_docker.tar

      - store_artifacts:
          path: ./fpyi_docker.tar

      # Build kwiver wheel image
      - run:
          name: "Build Kwiver Wheel Image"
          command: |
            docker build --force-rm -t "$DOCKERHUB_USERNAME"/kwiver_py37 -f Dockerfile.kwiver .

      - run:
          name: "Gather Kwiver Wheel"
          command: |
            chmod +x run_docker.sh
            ./run_docker.sh

      - store_artifacts:
          path: ~/kwiver_wheels/pages
      - run:
          name: "Archive Kwiver Docker Image"
          command: docker save "$DOCKERHUB_USERNAME"/kwiver_py37:latest | pv > kpyi_docker.tar
      - store_artifacts:
          path: ./kpyi_docker.tar

      - run:
          name: "Upload Kwiver Docker Image"
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$dockerhubtoken"
            docker push "$DOCKERHUB_USERNAME"/kwiver_py37:latest

      - run:
          name: "Checkout Pages"
          command: |
            git checkout -f -B pages --track origin/pages
      - run:
          name: "Upload Wheels"
          command: |
            cd pages
            git add *.whl && git add index.html && git commit -m"Upload Wheel" && git push -f
      - run:
          name: "tar wheels for archiving"
          command: |
            tar -cvzf kwiver-wheels.tar ./pages
      - store_artifacts:
          path: kwiver-wheels.tar
workflows:
  # Orchestrate or schedule a set of jobs
  version: 2
  Build-Kwiver-Wheels:
      jobs:
        - build-wheel:
            filters:
              branches:
                only: master
          
