name: BuildWheel

on:
  push:
    branches:
      - master



jobs:
  build-wheel:
    name: Wheel Builder
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ~/kwiver_wheels
    steps:
      - name: Checkout Wheels Repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: "Install pv"
          run: |
            sudo apt-get update
            sudo apt-get install -y pv
      - name: "Setup Docker"
          run: |
            docker pull quay.io/pypa/manylinux2014_x86_64:latest

      # Get fletch current HEAD commit SHA
      - name: "Check Fletch update"
          run: |
            git ls-remote https://github.com/kitware/fletch.git | awk "/HEAD/ {print \$1}" > checkFletch

      # Validate vs cached check
      - name: Restore Fletch Cache
        uses: actions/cache@v2
        with:
          key: fletch-${{ hashFiles('**/checkFletch') }}
          path: ./fpyi_docker.tar
      # Build fletch image
      - name: "Build Fletch Image"
          run: |
            chmod +x build_fletch.sh
            ./build_fletch.sh

      - name: "Archive Fletch Docker Image"
          run: docker save fletch_py37:latest | pv > fpyi_docker.tar

      - name: "Store Fletch Docker Image"
        uses: actions/upload-artifact@v2
        with:
          path: ./fpyi_docker.tar

      # Build kwiver wheel image
      - name: "Build Kwiver Wheel Image"
          env:
            DOCKERHUB_USERNAME: ${{ secrets.dockerhub_username }}
          run: |
            docker build --force-rm -t "$DOCKERHUB_USERNAME"/kwiver_py37 -f Dockerfile.kwiver .

      - name: "Archive Kwiver Docker Image"
          env:
            DOCKERHUB_USERNAME: ${{ secrets.dockerhub_username }}
          run: docker save "$DOCKERHUB_USERNAME"/kwiver_py37:latest | pv > kpyi_docker.tar

      - name: "Store Kwiver Docker Image"
          uses: actions/upload-artifact@v2
          with:
            path: ./kpyi_docker.tar

      - name: "Upload Kwiver Docker Image"
          env:
            DOCKERHUB_USERNAME: ${{ secrets.dockerhub_username }}
            DOCKERHUB_TOKEN: ${{ secrets.dockerhub_token }}
          run: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
            docker push "$DOCKERHUB_USERNAME"/kwiver_py37:latest

      - name: "Gather Kwiver Wheel"
          run: |
            chmod +x run_docker.sh
            ./run_docker.sh

      - name: "Checkout Pages"
          run: |
            git checkout -f -B pages --track origin/pages

      - name: "Upload Wheels"
          run: |
            cd pages
            git add *.whl && git add index.html && git commit -m"Upload Wheel" && git push -f

      - name: "tar wheels for archiving"
          run: |
            tar -cvzf kwiver-wheels.tar ./pages

      - name: Store Kwiver Wheels
        uses: actions/upload-artifact@v2
        with:
          path: kwiver-wheels.tar
